### ISSUE TITLE
关于学生邮箱的一个小问题

### ISSUE THREAD

**Issue by SherkeyXD** [rogerchenfz/XMU-Helper#7]
本来打算写一篇用Outlook收学生邮箱邮件的指南，但是发现smtp似乎用不了
收信正常，发信就发不出去了
有人知道是什么原因咩
使用smtp地址: `smtp.stu.xmu.edu.cn`

**Comment by whxdtr** [comment]
我所用的一切正常，可能是校园网的问题，你可以试着连上vpn。
祝好！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 孙胤真 ***@***.***&gt;
发送时间: 2022年8月31日 01:26
收件人: XMU-Helper/home ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [XMU-Helper/home] 关于学生邮箱的一个小问题 (Issue #7)





 
本来打算写一篇用Outlook收学生邮箱邮件的指南，但是发现smtp似乎用不了
 收信正常，发信就发不出去了
 有人知道是什么原因咩
 使用smtp地址: smtp.stu.xmu.edu.cn

**Comment by rogerchenfz** [comment]
可以参见这篇推送：https://mp.weixin.qq.com/s/VgwEEUi3G7rJMYfYfZNL6w
